In [48]:
from IPython.display import Image
import numpy as np

# [The Basics](https://numpy.org/doc/stable/user/quickstart.html#the-basics)

NumPyではN次元のarrayを扱います。各次元のことをaxisと呼びます。

以下の例ではfirst axisの長さは2で、second axisの長さは3です。次元は一番外のカッコからfirst、second、、、と数えると覚えておきましょう。
```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
```

# [An example](https://numpy.org/doc/stable/user/quickstart.html#an-example)

In [37]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
a.shape

(3, 5)

In [44]:
a.ndim # 次元数。つまりaxisの数。

2

In [49]:
a.dtype

dtype('int64')

In [45]:
a.dtype.name

'int64'

In [46]:
a.itemsize # 各要素のbyte数。

8

In [42]:
a.size

15

In [43]:
type(a)

numpy.ndarray

# [Array Creation](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

`array`関数を使ってPythonのリストからarrayを作成します。

In [51]:
a = np.array([2, 3, 4])
b = np.array([1.2, 3.5, 5.1])

In [52]:
a.dtype

dtype('int64')

In [53]:
b.dtype

dtype('float64')

In [56]:
b = np.array([(1.5,2,3), (4,5,6)]) # 2次元以上のarrayもこのように作れる。
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [58]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

サイズを指定してarrayを作成する関数もあります。

In [59]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [168]:
np.empty( (2,3), )                                 # uninitialized
# メモリの状況に依存してランダムに初期化されるらしい。

array([[5.92878775e-323, 2.00000000e+000, 5.10959527e-158],
       [4.00000000e+000, 1.19787521e-002, 6.00000000e+000]])

`range`関数と同じような挙動の`arange`関数もあります。

In [169]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [170]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

`arange`関数の引数に小数点を指定した場合に、有限の小数点の精度の限界があるので要素数が予想と異なる場合があります。そのため、`linespace`関数を使う方が望ましいです。

In [206]:
# 例えば次の二つは同じ結果になる。
print(np.arange(0, 7/3, 1/3))
print(np.arange(0, 8/3, 1/3))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333]


In [171]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [210]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

以下のように実行すれば上の例で予想していなかった挙動は回避できます。

In [209]:
print(np.linspace(0, 7/3, 8))
print(np.linspace(0, 8/3, 9))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667]


# [Printing Arrays](https://numpy.org/doc/stable/user/quickstart.html#printing-arrays)

In [213]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [214]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [215]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [216]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [217]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [219]:
print(np.arange(2**10).reshape(2, 2, 2, 2, 2, 2, 2, 2, 2, 2)) # 次元は省略されないらしい・・・それもそうか。

[[[[[[[[[[   0    1]
         [   2    3]]

        [[   4    5]
         [   6    7]]]


       [[[   8    9]
         [  10   11]]

        [[  12   13]
         [  14   15]]]]



      [[[[  16   17]
         [  18   19]]

        [[  20   21]
         [  22   23]]]


       [[[  24   25]
         [  26   27]]

        [[  28   29]
         [  30   31]]]]]




     [[[[[  32   33]
         [  34   35]]

        [[  36   37]
         [  38   39]]]


       [[[  40   41]
         [  42   43]]

        [[  44   45]
         [  46   47]]]]



      [[[[  48   49]
         [  50   51]]

        [[  52   53]
         [  54   55]]]


       [[[  56   57]
         [  58   59]]

        [[  60   61]
         [  62   63]]]]]]





    [[[[[[  64   65]
         [  66   67]]

        [[  68   69]
         [  70   71]]]


       [[[  72   73]
         [  74   75]]

        [[  76   77]
         [  78   79]]]]



      [[[[  80   81]
         [  82   83]]

        [[  84   85]
         [  86   87

以下の設定をすると全ての要素を表示するようになるらしいのですが、面倒なので未確認です。
```python
np.set_printoptions(threshold=sys.maxsize)       # sys module should be imported
```


# [Basic Operations](https://numpy.org/doc/stable/user/quickstart.html#basic-operations)

演算は要素ごとに実行されます。

In [220]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [221]:
c = a-b
c

array([20, 29, 38, 47])

In [222]:
b**2

array([0, 1, 4, 9])

In [223]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [224]:
a<35

array([ True,  True, False, False])

In [227]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )

In [228]:
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [229]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [230]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

代入演算子も使えます。

In [232]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [233]:
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [234]:
b += a

In [235]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

型の変換は自動的に行われないことに注意しましょう。

In [236]:
a += b                            # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

異なるデータ型のarray同士の演算の結果、データ型はに[アップキャスティング](https://e-words.jp/w/%E3%82%AD%E3%83%A3%E3%82%B9%E3%83%88.html)により変化します。

In [238]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [239]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [240]:
c.dtype.name

'float64'

In [241]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [242]:
d.dtype.name

'complex128'

In [243]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

以下のようなメソッドも実装されています。

In [244]:
a.sum()

3.1057109529998157

In [245]:
a.min()

0.027559113243068367

In [246]:
a.max()

0.8277025938204418

In [247]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [248]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [249]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [250]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# [Universal Functions](https://numpy.org/doc/stable/user/quickstart.html#universal-functions)

In [251]:
B = np.arange(3)
B

array([0, 1, 2])

In [252]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [253]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [255]:
C = np.array([2., -1., 4.])

In [256]:
np.add(B, C)

array([2., 0., 6.])

ufancはここを参照してください。

[Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)

# [Indexing, Slicing and Iterating](https://numpy.org/doc/stable/user/quickstart.html#the-basics)

In [257]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [258]:
a[2]

8

In [259]:
a[2:5]

array([ 8, 27, 64])

In [260]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [261]:
a[ : :-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [262]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


多次元のarrayのインデックスはカンマで区切って与えらられます。

In [263]:
def f(x,y):
    return 10*x+y

In [264]:
b = np.fromfunction(f,(5,4),dtype=int)

In [265]:
b[2,3]

23

In [266]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [267]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [268]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

指定したインデックスが次元よりも少ない場合は自動的にcomplete slices (:のこと) に変換されます。

In [270]:
b[-1]                             # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

`...`を使うことで:を省略することができます。

- `x[1,2,...]` is equivalent to `x[1,2,:,:,:]`,
- `x[...,3]` to `x[:,:,:,:,3]` and
- `x[4,...,5,:]` to `x[4,:,:,5,:]`.

In [271]:
c = np.array( [[[  0,  1,  2],   # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

In [272]:
c.shape

(2, 2, 3)

In [273]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [274]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

イテレートは第一次元について実行されます。

In [275]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [276]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


See also

[Indexing](https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing), [Indexing (reference)](https://numpy.org/doc/stable/reference/arrays.indexing.html#arrays-indexing), [newaxis](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis), [ndenumerate](https://numpy.org/doc/stable/reference/generated/numpy.ndenumerate.html#numpy.ndenumerate), [indices](https://numpy.org/doc/stable/reference/generated/numpy.indices.html#numpy.indices)